
import React,{useState,useEffect}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const K="olitech_v44_db",LEG=["olitech_v43_db","olitech_v42_db","olitech_db","olitech_erp_v41_db"];
const uid=(p="id")=>`${p}_${Date.now()}_${Math.floor(Math.random()*99999)}`;
const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().trim();
const num=v=>Number(String(v||0).replace(/[R$\s]/g,"").replace(/\./g,"").replace(",", "."))||0;
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(date,days)=>{const d=new Date(`${date||today()}T00:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const status=s=>({"FECHADO":"FINALIZADA","FECHADA":"FINALIZADA","FINALIZADO":"FINALIZADA","ATENDIDA":"FINALIZADA","EM ANDAMENTO":"EM ATENDIMENTO","ANDAMENTO":"EM ATENDIMENTO","ABERTO":"ABERTA","CANCELADO":"CANCELADA"}[norm(s||"ABERTA")]||norm(s||"ABERTA"));
const pago=s=>["PAGO","QUITADO","CANCELADO","FINALIZADA"].includes(status(s));
function vazio(){return{config:{versao:"V44",empresaNome:"OLITECH",telefone:"(16) 99607-6918",logo:"",whatsapp:{baseUrl:"",apiKey:"",instance:"olitech",numero:""},cobranca:{ativo:false,diasAntes:1,horaInicio:"09:00",horaFim:"18:00",vezesDia:2,pixChave:"",pixNome:"",linkPagamento:""}},clientes:[{id:"consumidor",nome:"CONSUMIDOR",telefone:""}],produtos:[],fornecedores:[],usuarios:[{id:"admin",nome:"OLITECH",usuario:"olitech",senha:"051309",perfil:"admin",ativo:true,permissoes:["*"]}],ordens:[],vendas:[],financeiro:[],campanhas:[],agendamentosOS:[],cobrancasLog:[],nfe:[]}}
function normaliza(db){db={...vazio(),...(db||{})};["clientes","produtos","fornecedores","usuarios","ordens","vendas","financeiro","campanhas","agendamentosOS","cobrancasLog","nfe"].forEach(x=>db[x]=Array.isArray(db[x])?db[x]:[]);db.config={...vazio().config,...(db.config||{})};db.config.versao="V44";db.config.whatsapp={...vazio().config.whatsapp,...(db.config.whatsapp||{})};db.config.cobranca={...vazio().config.cobranca,...(db.config.cobranca||{})};return db}
function carrega(){for(const k of[K,...LEG]){try{const r=localStorage.getItem(k);if(r){const d=normaliza(JSON.parse(r));salva(d);return d}}catch(e){}}const d=vazio();salva(d);return d}
function salva(db){const d=normaliza(db);localStorage.setItem(K,JSON.stringify(d));localStorage.setItem("olitech_db",JSON.stringify(d));return d}
const MENU=[["painel","📊","Painel"],["os","🧾","O.S."],["vendas","🛒","Vendas/PDV"],["clientes","👥","Clientes"],["produtos","📦","Produtos"],["fornecedores","🚚","Fornecedores"],["financeiro","💰","Financeiro"],["fiscal","🧾","Fiscal/NF-e"],["campanhas","📣","Campanhas"],["whatsapp","🟢","WhatsApp"],["relatorios","📈","Relatórios"],["usuarios","👥","Usuários"],["backup","💾","Backup"],["personalizacao","🎨","Personalização"],["cobrancas","💬","Cobranças"]];
function App(){const[db,setDbS]=useState(carrega),[page,setPageS]=useState(localStorage.getItem("olitech_v44_page")||"painel"),[mobile,setMobile]=useState(false),[sobre,setSobre]=useState(false),[sess,setSess]=useState(()=>JSON.parse(localStorage.getItem("olitech_v44_session")||"null"));useEffect(()=>{document.title="Olitech ERP V44"},[]);const setDb=u=>setDbS(p=>salva(typeof u==="function"?u(p):u));const setPage=p=>{localStorage.setItem("olitech_v44_page",p);setPageS(p);setMobile(false);window.scrollTo(0,0)};if(!sess)return <Login db={db} setSess={setSess}/>;return <div className="app"><button className="mobileBtn" onClick={()=>setMobile(!mobile)}>☰ Menu</button><aside className={mobile?"side open":"side"}><div className="brand"><Logo db={db}/><div><b>{db.config.empresaNome}</b><small>Sistema ERP/O.S.</small></div></div><button className="about" onClick={()=>setSobre(true)}>ℹ Sobre</button>{MENU.map(m=><button key={m[0]} className={page===m[0]?"active":""} onClick={()=>setPage(m[0])}>{m[1]} {m[2]}</button>)}<button onClick={()=>{localStorage.removeItem("olitech_v44_session");setSess(null)}}>Sair</button></aside><main className="main"><div className="top"><h1>{MENU.find(m=>m[0]===page)?.[1]} {MENU.find(m=>m[0]===page)?.[2]}</h1><div><button onClick={()=>setPage("painel")}>🏠 Início</button><button onClick={()=>setPage("painel")}>↩ Voltar</button></div></div><Pagina page={page} db={db} setDb={setDb} setPage={setPage}/></main>{sobre&&<div className="modalBg" onClick={e=>{if(e.target.className==="modalBg")setSobre(false)}}><div className="modalBox"><button onClick={()=>setSobre(false)}>Fechar</button><img className="sobreImg" src="/olitech-sobre.png?v=44"/></div></div>}</div>}
function Login({db,setSess}){const[u,setU]=useState("olitech"),[s,setS]=useState("051309");function entrar(){const user=db.usuarios.find(x=>norm(x.usuario)===norm(u)&&String(x.senha)===String(s)&&x.ativo!==false);if(!user)return alert("Usuário ou senha inválidos");localStorage.setItem("olitech_v44_session",JSON.stringify(user));setSess(user)}return <div className="login"><section className="card"><h1>Olitech ERP V44</h1><p className="info">Login padrão: olitech / 051309</p><label>Usuário<input value={u} onChange={e=>setU(e.target.value)}/></label><label>Senha<input type="password" value={s} onChange={e=>setS(e.target.value)}/></label><button onClick={entrar}>Entrar</button></section></div>}
function Logo({db}){return <div className="logo">{db.config.logo?<img src={db.config.logo}/>:"OL"}</div>}
function Pagina({page,db,setDb,setPage}){const props={db,setDb,setPage};return({painel:<Painel {...props}/>,clientes:<Crud title="Clientes" keyName="clientes" fields={["nome","telefone","cpf","cnpj","endereco","cidade","estado"]}{...props}/>,produtos:<Produtos {...props}/>,fornecedores:<Crud title="Fornecedores" keyName="fornecedores" fields={["nome","telefone","cnpj","email","endereco","cidade","estado","pix"]}{...props}/>,usuarios:<Crud title="Usuários" keyName="usuarios" fields={["nome","usuario","senha","perfil","ativo","permissoes"]}{...props}/>,os:<OS {...props}/>,vendas:<Vendas {...props}/>,financeiro:<Crud title="Financeiro" keyName="financeiro" fields={["tipo","descricao","valor","vencimento","status","cliente","telefone"]}{...props}/>,fiscal:<Fiscal/>,campanhas:<Campanhas/>,whatsapp:<WhatsApp {...props}/>,relatorios:<Relatorios db={db}/>,backup:<Backup {...props}/>,personalizacao:<Personalizacao {...props}/>,cobrancas:<Cobrancas {...props}/>}[page]||<Painel {...props}/>)}
function KPI({t,v}){return <div className="kpi"><b>{t}</b><strong>{v}</strong></div>}
function Painel({db,setPage}){const abertas=db.ordens.filter(o=>!pago(o.status)).length;const vendasHoje=db.vendas.filter(v=>(v.data||v.dataVenda)===today()).reduce((a,v)=>a+num(v.total),0);const pend=getPend(db);const agHoje=db.agendamentosOS.filter(a=>a.status!=="CONCLUIDO"&&a.status!=="CANCELADO"&&a.data===today());const agAberto=db.agendamentosOS.filter(a=>a.status!=="CONCLUIDO"&&a.status!=="CANCELADO");return <><section className="hero"><Logo db={db}/><div><h2>{db.config.empresaNome} - SISTEMA ERP/O.S.</h2><p>ERP com O.S., PDV, financeiro, WhatsApp, campanhas, backup e fiscal.</p></div></section><section className="cards"><KPI t="O.S. abertas" v={abertas}/><KPI t="Clientes" v={db.clientes.length}/><KPI t="Produtos" v={db.produtos.length}/><KPI t="Vendas hoje" v={money(vendasHoje)}/><KPI t="Contas em atraso" v={pend.length}/><KPI t="Agendamentos hoje" v={agHoje.length}/><KPI t="Total agendado" v={agAberto.length}/></section><section className="card"><h3>Atalhos rápidos</h3><button onClick={()=>setPage("os")}>+ Nova O.S.</button><button onClick={()=>setPage("vendas")}>+ Nova Venda</button><button onClick={()=>setPage("clientes")}>+ Novo Cliente</button><button onClick={()=>setPage("whatsapp")}>WhatsApp</button></section></>}
function Crud({title,keyName,fields,db,setDb}){const[form,setForm]=useState({}),[q,setQ]=useState(""),[all,setAll]=useState(false);const rows=(db[keyName]||[]).filter(x=>all||(q.length>=2&&norm(JSON.stringify(x)).includes(norm(q)))).slice(0,300);function salvar(){if(!fields.some(f=>form[f]))return alert("Preencha os dados.");const obj={...form,id:form.id||uid(keyName)};setDb(d=>({...d,[keyName]:[...(d[keyName]||[]).filter(x=>x.id!==obj.id),obj]}));setForm({})}function del(id){if(confirm("Excluir?"))setDb(d=>({...d,[keyName]:(d[keyName]||[]).filter(x=>x.id!==id)}))}return <><section className="card"><h2>{form.id?"Editar":"Novo"} {title}</h2><div className="grid">{fields.map(f=><label key={f}>{f}<input value={form[f]||""} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>)}</div><button onClick={salvar}>Salvar</button><button className="secondary" onClick={()=>setForm({})}>Limpar</button></section><section className="card"><h3>Pesquisar {title}</h3><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite pelo menos 2 caracteres"/><button onClick={()=>setAll(true)}>Mostrar todos</button></div>{rows.length?<div className="list">{rows.map(r=><div className="row" key={r.id}><div><b>{r.nome||r.usuario||r.descricao||"SEM NOME"}</b><small>{fields.map(f=>r[f]).filter(Boolean).slice(0,5).join(" | ")}</small></div><div className="actions"><button onClick={()=>setForm(r)}>Editar</button><button className="danger" onClick={()=>del(r.id)}>Excluir</button></div></div>)}</div>:<p className="info">Digite 2 caracteres ou clique em Mostrar todos.</p>}</section></>}
function Produtos({db,setDb}){return <Crud title="Produtos" keyName="produtos" fields={["nome","codigoBarras","fornecedor","categoria","custo","venda","margem","estoque","ncm","cfop"]} db={db} setDb={setDb}/>}
function BuscaProduto({db,onAdd}){const[q,setQ]=useState("");const list=db.produtos.filter(p=>q.length>=2&&norm(JSON.stringify(p)).includes(norm(q))).slice(0,30);return <section className="card soft"><h3>Adicionar produto/serviço</h3><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite produto ou código"/>{list.map(p=><button key={p.id} onClick={()=>{onAdd({id:p.id,nome:p.nome,qtd:1,valor:num(p.venda||p.valor)});setQ("")}}>{p.nome} - {money(p.venda||p.valor)}</button>)}</section>}
function Itens({itens,setItens}){return <div className="list">{itens.map((i,idx)=><div className="row" key={idx}><div><b>{i.nome}</b><small>{money(num(i.valor)*num(i.qtd||1))}</small></div><input value={i.qtd} onChange={e=>{let a=[...itens];a[idx].qtd=e.target.value;setItens(a)}}/><input value={i.valor} onChange={e=>{let a=[...itens];a[idx].valor=e.target.value;setItens(a)}}/><button className="danger" onClick={()=>setItens(itens.filter((_,j)=>j!==idx))}>Remover</button></div>)}</div>}
function Parcelas({total,onChange}){const[entrada,setEntrada]=useState(0),[qtd,setQtd]=useState(1),[venc,setVenc]=useState(today());function gerar(){const saldo=Math.max(0,num(total)-num(entrada));const q=Math.max(1,Number(qtd||1));const valor=saldo/q;const arr=Array.from({length:q},(_,i)=>({id:uid("parc"),n:i+1,valor,vencimento:addDays(venc,i*30),status:"ABERTO"}));onChange(arr);alert("Parcelas/carnê gerados.")}return <section className="card soft"><h3>Parcelamento / Carnê / Promissória</h3><div className="grid"><label>Entrada R$<input value={entrada} onChange={e=>setEntrada(e.target.value)}/></label><label>Parcelas<input type="number" value={qtd} onChange={e=>setQtd(e.target.value)}/></label><label>Primeiro vencimento<input type="date" value={venc} onChange={e=>setVenc(e.target.value)}/></label></div><button onClick={gerar}>Gerar parcelas</button></section>}
function OS({db,setDb}){const[f,setF]=useState({tipo:"ORÇAMENTO",cliente:"CONSUMIDOR",status:"ABERTA",garantia:"7 DIAS",itens:[],parcelas:[]});const total=f.itens.reduce((a,i)=>a+num(i.valor)*num(i.qtd||1),num(f.valor));function salvar(){const os={...f,id:uid("os"),numeroOS:f.numeroOS||String(Date.now()).slice(-6),total,valor:total,status:status(f.status)};setDb(d=>({...d,ordens:[...d.ordens,os],agendamentosOS:f.agendamentoData?[...d.agendamentosOS,{id:uid("ag"),osId:os.id,numeroOS:os.numeroOS,cliente:os.cliente,tipo:f.agendamentoTipo||"BUSCAR",data:f.agendamentoData,hora:f.agendamentoHora,observacao:f.agendamentoObs,status:"AGENDADO"}]:d.agendamentosOS}));alert("O.S. salva.")}return <section className="card"><h2>Ordem de Serviço</h2><div className="grid">{["tipo","cliente","telefone","aparelho","imei","senha","defeito","laudo","status","garantia"].map(k=><label key={k}>{k}<input value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><BuscaProduto db={db} onAdd={p=>setF({...f,itens:[...f.itens,p]})}/><Itens itens={f.itens} setItens={itens=>setF({...f,itens})}/><section className="card soft"><h3>Agendamento da O.S.</h3><div className="grid"><label>Tipo<input value={f.agendamentoTipo||""} onChange={e=>setF({...f,agendamentoTipo:e.target.value})}/></label><label>Data<input type="date" value={f.agendamentoData||""} onChange={e=>setF({...f,agendamentoData:e.target.value})}/></label><label>Hora<input type="time" value={f.agendamentoHora||""} onChange={e=>setF({...f,agendamentoHora:e.target.value})}/></label><label>Obs<input value={f.agendamentoObs||""} onChange={e=>setF({...f,agendamentoObs:e.target.value})}/></label></div></section><Parcelas total={total} onChange={p=>setF({...f,parcelas:p})}/><h2>Total: {money(total)}</h2><button onClick={salvar}>Salvar O.S.</button></section>}
function Vendas({db,setDb}){const[f,setF]=useState({cliente:"CONSUMIDOR",status:"ABERTO",desconto:0,itens:[],parcelas:[]});const total=f.itens.reduce((a,i)=>a+num(i.valor)*num(i.qtd||1),0)-num(f.desconto);function salvar(){setDb(d=>({...d,vendas:[...d.vendas,{...f,id:uid("v"),numero:"V_"+String(Date.now()).slice(-6),total,statusFinanceiro:f.status,data:today()}]}));alert("Venda salva.")}return <section className="card"><h2>Vendas/PDV</h2><div className="grid"><label>Cliente<input value={f.cliente} onChange={e=>setF({...f,cliente:e.target.value})}/></label><label>Desconto R$<input value={f.desconto} onChange={e=>setF({...f,desconto:e.target.value})}/></label><label>Status<input value={f.status} onChange={e=>setF({...f,status:e.target.value})}/></label></div><BuscaProduto db={db} onAdd={p=>setF({...f,itens:[...f.itens,p]})}/><Itens itens={f.itens} setItens={itens=>setF({...f,itens})}/><Parcelas total={total} onChange={p=>setF({...f,parcelas:p})}/><h2>Total: {money(total)}</h2><button onClick={salvar}>Finalizar venda</button></section>}
function getPend(db){let out=[];db.financeiro.forEach(x=>{if(!["PAGO","QUITADO","CANCELADO"].includes(norm(x.status))&&x.vencimento)out.push({...x,origem:"FINANCEIRO",valor:num(x.valor),cliente:x.cliente||x.descricao})});db.vendas.forEach(v=>(v.parcelas||[]).forEach(p=>{if(!["PAGO","QUITADO","CANCELADO"].includes(norm(p.status)))out.push({...p,origem:"VENDA",cliente:v.cliente,telefone:v.telefone})}));db.ordens.forEach(o=>(o.parcelas||[]).forEach(p=>{if(!["PAGO","QUITADO","CANCELADO"].includes(norm(p.status)))out.push({...p,origem:"O.S.",cliente:o.cliente,telefone:o.telefone})}));return out}
function Cobrancas({db,setDb}){const[c,setC]=useState(db.config.cobranca);const pend=getPend(db);const cobrar=pend.filter(p=>addDays(p.vencimento,-Number(c.diasAntes||1))===today()||p.vencimento<today());function salvar(){setDb(d=>({...d,config:{...d.config,cobranca:c}}));alert("Regra salva.")}return <section className="card"><h2>Cobrança WhatsApp + PIX</h2><section className="cards"><KPI t="Débitos" v={pend.length}/><KPI t="Cobrar hoje" v={cobrar.length}/></section><div className="grid">{["ativo","diasAntes","horaInicio","horaFim","vezesDia","pixChave","pixNome","linkPagamento"].map(k=><label key={k}>{k}<input value={c[k]||""} onChange={e=>setC({...c,[k]:e.target.value})}/></label>)}</div><button onClick={salvar}>Salvar regra</button><div className="list">{cobrar.map((p,i)=><div className="row" key={i}><b>{p.cliente} - {money(p.valor)}</b><small>{p.vencimento} | {p.origem}</small></div>)}</div></section>}
function WhatsApp({db,setDb}){const[w,setW]=useState(db.config.whatsapp);function salvar(){setDb(d=>({...d,config:{...d.config,whatsapp:w}}));alert("WhatsApp salvo.")}return <section className="card"><h2>WhatsApp Evolution</h2><div className="grid">{["baseUrl","apiKey","instance","numero"].map(k=><label key={k}>{k}<input value={w[k]||""} onChange={e=>setW({...w,[k]:e.target.value})}/></label>)}</div><button onClick={salvar}>Salvar</button><p className="info">Para trocar número, desconecte a instância no painel Evolution e gere novo QR Code.</p></section>}
function Fiscal(){function printDanfe(){let w=open("","_blank");w.document.write("<html><body><h1>DANFE TESTE - SEM VALOR FISCAL</h1><p>Documento de apresentação/homologação. Não transmitido à SEFAZ.</p><button onclick='print()'>Imprimir</button></body></html>");w.document.close()}return <section className="card"><h2>Fiscal / NF-e</h2><p className="info">Preparado para NF-e. Emissão real exige certificado A1 e integração fiscal.</p><button onClick={printDanfe}>Imprimir DANFE teste</button></section>}
const Campanhas=()=> <section className="card"><h2>Campanhas</h2><p>Campanhas via WhatsApp usando a configuração da aba WhatsApp.</p></section>;
const Relatorios=({db})=> <section className="card"><h2>Relatórios</h2><p>Clientes: {db.clientes.length}</p><p>Produtos: {db.produtos.length}</p><p>O.S.: {db.ordens.length}</p><p>Vendas: {db.vendas.length}</p><p>Financeiro: {db.financeiro.length}</p><button onClick={()=>print()}>Imprimir</button></section>;
function Backup({db,setDb}){function exp(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="backup-olitech-v44.json";a.click()}function imp(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>setDb(JSON.parse(r.result));r.readAsText(f)}return <section className="card"><h2>Backup</h2><button onClick={exp}>Exportar JSON</button><input type="file" accept=".json" onChange={imp}/></section>}
function Personalizacao({db,setDb}){const[c,setC]=useState(db.config);function salvar(){setDb(d=>({...d,config:c}));alert("Personalização salva.")}function logo(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>setC({...c,logo:r.result});r.readAsDataURL(f)}return <section className="card"><h2>Personalização</h2><div className="grid"><label>Nome da empresa<input value={c.empresaNome||""} onChange={e=>setC({...c,empresaNome:e.target.value})}/></label><label>Telefone<input value={c.telefone||""} onChange={e=>setC({...c,telefone:e.target.value})}/></label><label>Logo URL<input value={c.logo||""} onChange={e=>setC({...c,logo:e.target.value})}/></label><label>Logo local<input type="file" accept="image/*" onChange={logo}/></label></div><button onClick={salvar}>Salvar</button></section>}
createRoot(document.getElementById("root")).render(<App/>);
